from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/signup/", views.signup, name="signup"),
    path("dashboard/", views.dashboard_index, name="dashboard_index"),
    path("dashboard/<int:user_id>/accounts/", views.account_dashboard, name="account_dashboard"),
    path("dashboard/accounts/create/", views.AccountCreate.as_view(), name="account_create"),
    path("dashboard/<int:pk>/accounts/update/", views.AccountUpdate.as_view(), name="account_update"),
    path("dashboard/<int:pk>/accounts/delete/", views.AccountDelete.as_view(), name="account_delete"),
    path("dashboard/accounts/<int:user_id>/account_photo/", views.account_photo, name="account_photo"),
    path("dashboard/topics/", views.dashboard_topics, name="dashboard_topics"),
    path("topics/<int:topic_id>/", views.topics_detail, name="topics_detail"),
    path("topics/", views.TopicList.as_view(), name="topics_index"),
    path("topics/create/", views.TopicCreate.as_view(), name="topic_create"),
    path("topics/<int:pk>/update/", views.TopicUpdate.as_view(), name="topic_update"),
    path("topics/<int:pk>/delete/", views.TopicDelete.as_view(), name="topic_delete"),
    path("topics/<int:topic_id>/topic_photo/", views.topic_photo, name="topic_photo"),
    path("topics/<int:topic_id>/bookmark_topic/<int:user_id>/", views.bookmark_topic, name="bookmark_topic"),
    path("topics/<int:topic_id>/unbookmark_topic/<int:user_id>/", views.unbookmark_topic, name="unbookmark_topic"),
    path("topics/<int:topic_id>/add_tag/", views.add_tag, name="add_tag"),
    path("topics/<int:user_id>/<int:topic_id>/add_post/", views.add_post, name="add_post"),
    path("topics/<int:topic_id>/posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("topics/<int:topic_id>/posts/<int:pk>/update/", views.PostUpdate.as_view(), name="post_update"),
    path("topics/<int:topic_id>/posts/<int:pk>/delete/", views.PostDelete.as_view(), name="post_delete"),
    path("topics/<int:topic_id>/posts/<int:post_id>/post_photo/", views.post_photo, name="post_photo"),
    path("topics/<int:topic_id>/posts/<int:post_id>/upvote/<int:user_id>/", views.upvote_post, name="upvote_post"),
    path("topics/<int:topic_id>/posts/<int:post_id>/downvote/<int:user_id>/", views.downvote_post, name="downvote_post"),
    path("topics/<int:topic_id>/posts/<int:post_id>/unupvote/<int:user_id>/", views.unupvote_post, name="unupvote_post"),
    path("topics/<int:topic_id>/posts/<int:post_id>/undownvote/<int:user_id>/", views.undownvote_post, name="undownvote_post"),
    path("topics/<int:topic_id>/posts/<int:post_id>/upvotedetail/<int:user_id>/", views.upvote_postdetail, name="upvote_postdetail"),
    path("topics/<int:topic_id>/posts/<int:post_id>/downvotedetail/<int:user_id>/", views.downvote_postdetail, name="downvote_postdetail"),
    path("topics/<int:topic_id>/posts/<int:post_id>/unupvotedetail/<int:user_id>/", views.unupvote_postdetail, name="unupvote_postdetail"),
    path("topics/<int:topic_id>/posts/<int:post_id>/undownvotedetail/<int:user_id>/", views.undownvote_postdetail, name="undownvote_postdetail"),
    path("topics/<int:user_id>/<int:topic_id>/posts/<int:post_id>/add_comment/", views.add_comment, name="add_comment"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:pk>/update/", views.CommentUpdate.as_view(), name="comment_update"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:pk>/delete/", views.CommentDelete.as_view(), name="comment_delete"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:comment_id>/like/<int:user_id>/", views.like_comment, name="like_comment"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:comment_id>/dislike/<int:user_id>/", views.dislike_comment, name="dislike_comment"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:comment_id>/unlike/<int:user_id>/", views.unlike_comment, name="unlike_comment"),
    path("topics/<int:topic_id>/posts/<int:post_id>/comments/<int:comment_id>/undislike/<int:user_id>/", views.undislike_comment, name="undislike_comment"),
]
