# Generated by Django 3.1.7 on 2021-03-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210304_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='account',
            name='post',
        ),
        migrations.RemoveField(
            model_name='account',
            name='topic',
        ),
        migrations.AddField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
            preserve_default=False,
        ),
    ]
