# Generated by Django 3.1.7 on 2021-03-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210304_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='account',
        ),
    ]
