# Generated by Django 3.1.7 on 2021-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210304_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='account',
            name='bookmark',
            field=models.ManyToManyField(to='main_app.Bookmark'),
        ),
        migrations.AddField(
            model_name='topic',
            name='bookmark',
            field=models.ManyToManyField(to='main_app.Bookmark'),
        ),
    ]
