# Generated by Django 3.1.7 on 2021-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210306_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='account',
            name='bookmarks',
            field=models.ManyToManyField(to='main_app.Topic'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
