# Generated by Django 3.1.7 on 2021-03-11 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topics',
        ),
        migrations.AddField(
            model_name='tag',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.topic'),
        ),
    ]
